version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "factory_bot"
          - "github_changelog_generator"
          - "jsonapi-rspec"
          - "rspec-rails"
          - "shoulda-matchers"
        update-types:
          - "minor"
          - "patch"
      lint:
        patterns:
          - "rubocop"
          - "standard"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    groups:
      babel:
        patterns:
          - "@babel/core"
          - "@babel/preset-env"
      jest:
        patterns:
          - "jest"
          - "babel-jest"
