# frozen_string_literal: true

require "alchemy/json_api/ingredient_serializer"

module Alchemy
  module JsonApi
    # Generates TypeScript types of the deserialized API responses
    # from the element and page layout definitions of the app.
    class TypescriptGenerator
      class TypeNameCollisionError < StandardError; end

      HEADER = "// This file is generated by `bin/rails alchemy:json_api:generate_types`. Do not edit it by hand."

      RECORD_TYPES = {
        "element" => "AlchemyElement",
        "language" => "AlchemyLanguage",
        "node" => "AlchemyNode",
        "page" => "AlchemyPage"
      }.freeze

      def generate
        ensure_unique_type_names!(element_definitions, "Element") { element_type_name(_1) }
        ensure_unique_type_names!(page_definitions, "Page layout") { page_type_name(_1) }

        [
          HEADER,
          interface("AlchemyLanguage", properties(LanguageSerializer)),
          interface("AlchemyNode", properties(NodeSerializer)),
          *ingredient_types.map { ingredient_interface(_1) },
          interface("AlchemyElementBase", properties(ElementSerializer, except: %w[name ingredients nested_elements])),
          *element_definitions.map { element_interface(_1) },
          union("AlchemyElement", element_definitions.map { element_type_name(_1) }),
          union("AlchemyElementName", element_definitions.map { _1.name.to_json }),
          interface("AlchemyPageBase", properties(PageSerializer, except: %w[page_layout elements fixed_elements])),
          *page_definitions.map { page_interface(_1) },
          union("AlchemyPage", page_definitions.map { page_type_name(_1) }),
          union("AlchemyPageLayout", page_definitions.map { _1.name.to_json })
        ].join("\n\n") + "\n"
      end

      private

      def ensure_unique_type_names!(definitions, kind, &type_name)
        definitions.group_by(&type_name).each do |name, collisions|
          next if collisions.one?

          raise TypeNameCollisionError,
            "#{kind} definitions #{collisions.map(&:name).join(", ")} would all generate the TypeScript type #{name}. Please rename them."
        end
      end

      def element_definitions
        @_element_definitions ||= Alchemy::ElementDefinition.all
      end

      def page_definitions
        @_page_definitions ||= Alchemy::PageDefinition.all
      end

      def ingredient_types
        element_definitions.flat_map(&:ingredients).map(&:type).uniq.sort
      end

      def ingredient_serializer(type)
        @_ingredient_serializers ||= {}
        @_ingredient_serializers[type] ||= "Alchemy::JsonApi::Ingredient#{type}Serializer".safe_constantize ||
          Class.new(BaseSerializer) { include IngredientSerializer }
      end

      def ingredient_interface(type)
        interface(ingredient_type_name(type), properties(ingredient_serializer(type)))
      end

      def element_interface(definition)
        interface(element_type_name(definition), [
          [key_for(ElementSerializer, "name"), definition.name.to_json],
          narrowed_relationship(ElementSerializer, "ingredients", ingredients_type(definition)),
          narrowed_relationship(ElementSerializer, "nested_elements", elements_type(defined_elements(definition.nestable_elements)))
        ], extends: "AlchemyElementBase")
      end

      def page_interface(definition)
        fixed, non_fixed = defined_elements(definition.elements).partition(&:fixed)
        interface(page_type_name(definition), [
          [key_for(PageSerializer, "page_layout"), definition.name.to_json],
          narrowed_relationship(PageSerializer, "elements", elements_type(non_fixed)),
          narrowed_relationship(PageSerializer, "fixed_elements", elements_type(fixed))
        ], extends: "AlchemyPageBase")
      end

      def ingredients_type(definition)
        return "never[]" if definition.ingredients.empty?

        members = definition.ingredients.map do |ingredient|
          serializer = ingredient_serializer(ingredient.type)
          narrowing = ["#{property_key(key_for(serializer, "role"))}: #{ingredient.role.to_json}"]
          if (value_type = select_value_type(ingredient))
            narrowing << "#{property_key(key_for(serializer, "value"))}: #{value_type}"
          end
          "    | (#{ingredient_type_name(ingredient.type)} & { #{narrowing.join("; ")} })"
        end
        "Array<\n#{members.join("\n")}\n  >"
      end

      def select_value_type(ingredient)
        return unless ingredient.type == "Select"

        values = select_values(ingredient.settings[:select_values])
        return if values.blank?

        literals = values.map(&:to_s).uniq.map(&:to_json).join(" | ")
        ingredient.settings[:multiple] ? "Array<#{literals}>" : "#{literals} | null"
      end

      def select_values(values)
        case values
        when Hash then values.values.flat_map { select_values(_1) }
        when Array then values.map { _1.is_a?(Array) ? _1.last : _1 }
        end
      end

      def defined_elements(names)
        Array(names).uniq.filter_map { |name| element_definitions.detect { _1.name == name } }
      end

      def elements_type(definitions)
        return "never[]" if definitions.empty?

        "Array<#{definitions.map { element_type_name(_1) }.join(" | ")}>"
      end

      def properties(serializer, except: [])
        attributes = serializer.attributes_to_serialize.to_h.values.map do |attribute|
          type = serializer.typelized_attributes.fetch(attribute.key.to_s.underscore, "unknown")
          [attribute.key, type, attribute.conditional_proc.present?]
        end
        relationships = serializer.relationships_to_serialize.to_h.values.map do |relationship|
          [relationship.key, relationship_type(relationship), relationship.conditional_proc.present?]
        end
        [["id", "string", false], *attributes, *relationships].reject do |key, _|
          except.include?(key.to_s.underscore)
        end
      end

      def narrowed_relationship(serializer, name, type)
        relationship = serializer.relationships_to_serialize.to_h.values.detect { _1.key.to_s.underscore == name }
        [relationship.key, relationship_type(relationship, type), relationship.conditional_proc.present?]
      end

      def relationship_type(relationship, type = nil)
        has_many = relationship.relationship_type == :has_many
        type ||= begin
          record_type = relationship.record_type || relationship.key.to_s.underscore.singularize
          target = RECORD_TYPES.fetch(record_type.to_s, "unknown")
          has_many ? "#{target}[]" : target
        end
        # Lazy relationships have no `data` unless included, which the deserializer turns into `null`.
        # A present conditional to-one relationship always has a record.
        nullable = relationship.lazy_load_data || (!has_many && relationship.conditional_proc.blank?)
        nullable ? "#{type} | null" : type
      end

      def key_for(serializer, name)
        keys = serializer.attributes_to_serialize.to_h.keys + serializer.relationships_to_serialize.to_h.values.map(&:key)
        keys.detect { _1.to_s.underscore == name }
      end

      def interface(name, properties, extends: nil)
        lines = properties.map do |key, type, optional|
          "  #{property_key(key)}#{"?" if optional}: #{type}"
        end
        "export interface #{name}#{" extends #{extends}" if extends} {\n#{lines.join("\n")}\n}"
      end

      def union(name, members)
        "export type #{name} = #{members.presence&.join(" | ") || "never"}"
      end

      def property_key(key)
        key.to_s.match?(/\A[A-Za-z_$][\w$]*\z/) ? key.to_s : key.to_s.to_json
      end

      def type_name(name)
        name.tr("-", "_").camelize
      end

      def element_type_name(definition)
        "Alchemy#{type_name(definition.name)}Element"
      end

      def page_type_name(definition)
        "Alchemy#{type_name(definition.name)}Page"
      end

      def ingredient_type_name(type)
        "AlchemyIngredient#{type}"
      end
    end
  end
end
