# frozen_string_literal: true

if ENV["OPENAPI"]
  require "rspec/openapi"

  RSpec::OpenAPI.path = File.expand_path("../../docs/openapi.yml", __dir__)
  RSpec::OpenAPI.title = "Alchemy CMS JSON API"
  RSpec::OpenAPI.application_version = Alchemy::JsonApi::VERSION
  RSpec::OpenAPI.info = {
    description: <<~DESC.strip,
      A JSON:API compliant API for AlchemyCMS.

      All responses follow the JSON:API specification. Use the `include` query parameter to
      sideload related resources, `filter` for Ransack-based filtering, and `page` for pagination.
    DESC
    license: {
      name: "BSD-3-Clause",
      url: "https://opensource.org/licenses/BSD-3-Clause"
    },
    contact: {
      name: "AlchemyCMS",
      url: "https://www.alchemy-cms.com/"
    }
  }

  RSpec::OpenAPI.comment = <<~COMMENT
    This file is auto-generated by rspec-openapi.
    Run `OPENAPI=1 bundle exec rspec` to regenerate.
  COMMENT

  RSpec::OpenAPI.servers = [{url: "/jsonapi", description: "Mounted engine path (default)"}]
  RSpec::OpenAPI.response_headers = %w[ETag Cache-Control Last-Modified]
  RSpec::OpenAPI.example_types = %i[request]

  # Exclude the openapi endpoint itself from generation
  RSpec::OpenAPI.ignored_paths = [/openapi/]

  # Tag endpoints by controller name
  RSpec::OpenAPI.tags_builder = ->(example) {
    controller = example.metadata.dig(:request, :controller) ||
      example.metadata[:described_class].to_s
    case controller
    when /Admin::LayoutPages/ then ["Admin Layout Pages"]
    when /Admin::Pages/ then ["Admin Pages"]
    when /LayoutPages/ then ["Layout Pages"]
    when /Nodes/ then ["Nodes"]
    when /Pages/ then ["Pages"]
    else []
    end
  }
end
