# frozen_string_literal: true

if ENV["OPENAPI"]
  require "rspec/openapi"

  RSpec::OpenAPI.path = File.expand_path("../../docs/openapi.yml", __dir__)
  RSpec::OpenAPI.title = "Alchemy CMS JSON API"
  RSpec::OpenAPI.application_version = Alchemy::JsonApi::VERSION
  RSpec::OpenAPI.info = {
    description: <<~DESC.strip,
      A [JSON:API](https://jsonapi.org/) compliant API for [AlchemyCMS](https://alchemy-cms.com).

      All responses follow the JSON:API specification. Use the `include` query parameter to
      sideload related resources, `filter` for Ransack-based filtering, and `page` for pagination.

      ## Authentication

      Public endpoints serve published content without authentication. Admin endpoints require
      an authenticated user with `edit_content` permission on `Alchemy::Page`.

      ## Caching

      Responses include HTTP caching headers (ETag, Cache-Control). Page endpoints default to
      a max-age of 600 seconds (configurable via `ALCHEMY_JSON_API_CACHE_DURATION` env var).
      Node endpoints default to 3 hours. Restricted pages are never publicly cached.
    DESC
    license: {
      name: "BSD-3-Clause",
      url: "https://opensource.org/licenses/BSD-3-Clause"
    },
    contact: {
      name: "AlchemyCMS",
      url: "https://www.alchemy-cms.com/"
    }
  }

  RSpec::OpenAPI.comment = <<~COMMENT
    This file is auto-generated by rspec-openapi.
    Run `OPENAPI=1 bundle exec rspec` to regenerate.
  COMMENT

  RSpec::OpenAPI.servers = [{url: "/jsonapi", description: "Mounted engine path (default)"}]
  RSpec::OpenAPI.response_headers = %w[ETag Cache-Control Last-Modified]
  RSpec::OpenAPI.example_types = %i[request]

  # Exclude the openapi and docs endpoints from generation
  RSpec::OpenAPI.ignored_paths = [/openapi/, /docs/]

  # Tag endpoints by controller name
  RSpec::OpenAPI.tags_builder = ->(example) {
    controller = example.metadata.dig(:request, :controller) ||
      example.metadata[:described_class].to_s
    case controller
    when /Admin::LayoutPages/ then ["Admin Layout Pages"]
    when /Admin::Pages/ then ["Admin Pages"]
    when /LayoutPages/ then ["Layout Pages"]
    when /Nodes/ then ["Nodes"]
    when /Pages/ then ["Pages"]
    else []
    end
  }
end
