- name: header
  unique: true
  ingredients:
    - role: image
      type: Picture

- name: headline
  ingredients:
    - role: headline
      type: Text

- name: article
  taggable: true
  ingredients:
    - role: intro
      type: Text
      deprecated: true
    - role: headline
      type: Text
      settings:
        linkable: true
    - role: image
      type: Picture
      settings:
        size: 450x300
        crop: true
        fixed_ratio: false
    - role: text
      type: Richtext

- name: text
  ingredients:
    - role: text
      type: Richtext

- name: search
  ingredients: []

- name: news
  ingredients:
    - role: date
      type: Datetime
    - role: news_headline
      type: Text
      rss_title: true
    - role: body
      type: Richtext
      rss_description: true

- name: download
  ingredients:
    - role: file
      type: File

- name: bild
  ingredients:
    - role: image
      type: Picture

- name: contactform
  unique: true
  ingredients:
    - role: mail_from
      type: Text
      validate:
        - presence
    - role: mail_to
      type: Text
      validate:
        - presence
    - role: subject
      type: Text
      as_element_title: true
      validate:
        - presence
    - role: success_page
      type: Page
      validate:
        - presence

- name: all_you_can_eat
  hint: true
  taggable: true
  ingredients:
    - role: text
      type: Text
      hint: true
    - role: picture
      type: Picture
      hint: true
    - role: richtext
      type: Richtext
      hint: true
    - role: select
      type: Select
      hint: true
      settings:
        select_values: [A, B, C]
    - role: boolean
      type: Boolean
      hint: true
    - role: date
      type: Datetime
      hint: true
    - role: file
      type: File
      hint: true
    - role: html
      type: Html
      hint: true
    - role: link
      type: Link
      hint: true

- name: <%= 'erb_' + 'element' %>
  ingredients:
    - role: text
      type: Richtext

- name: slide
  compact: true
  ingredients:
    - role: picture
      type: Picture
    - role: caption
      type: Text
      as_element_title: true

- name: slider
  nestable_elements:
    - slide
  autogenerate:
    - slide

- name: gallery
  nestable_elements:
    - gallery_picture

- name: gallery_picture
  compact: true
  ingredients:
    - role: picture
      type: Picture
      settings:
        size: 160x120

- name: right_column
  fixed: true
  unique: true
  ingredients:
    - role: title
      type: Text
  nestable_elements: [search, text]

- name: left_column
  fixed: true
  unique: true
  nestable_elements: [text]

- name: <%= 'erb_' + 'cell' %>
  fixed: true
  unique: true
  nestable_elements: [text]

- name: old
  deprecated: true
