name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-24.04
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4
      - name: Restore node modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('./package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm run build
